# Script to deploy on the Render platform

name: Node.js CI

on:
    push:
        branches: [ main ]
    pull request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: bounceapp/render-actions@0.6.0
            with:
                render-token: ${{secrets.RENDER_API_KEY}}
                github-token: ${{secrets.ACC_API_KEY}} #This is the GitHub token
                service-id: "srv-cg9d9ukeooghng7kla40" #This id is unique for each app
                retries: 20
                wait: 16000
                sleep: 30000
